apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-password: c2VuaGExMjM=  # valor codificado em base64 (senha fictícia)

# Comentário: Use `echo -n 'senha123' | base64` para gerar o valor codificado
