apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort  # Expõe a aplicação externamente pela porta do nó
  selector:
    app: minha-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080  # Porta no nó para acessar a aplicação
